name: CI (Pruebas Automatizadas)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12'
        cache: 'pnpm' 

    - name: Instalar dependencias
      run: pnpm install

    - name: Correr los tests
      run: pnpm test # 